name: Feature
description: Define a high-level capability or deliverable (Feature) for PlugHub, to be broken down into user stories and tasks.
title: "[Feature] <Short, descriptive title>"
labels: feature

body:
  - type: markdown
    attributes:
      value: |
        ## Feature

        Thank you for helping improve PlugHub! Please fill out the following details to help us understand your feature idea.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Briefly describe the feature or enhancement you are proposing.
      placeholder: e.g., "Add support for plugin dependency visualization."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / User Story
      description: |
        Explain why this feature is needed. Who will benefit from it?  
        (If relevant, use the user story format: "As a [user], I want [feature] so that [benefit].")
      placeholder: e.g., "As a plugin author, I want to visualize dependencies so that I can manage complex plugin relationships."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        List the requirements or conditions that must be met for this feature to be considered complete.
      placeholder: |
        - The UI displays a graph of plugin dependencies.
        - Users can click a plugin to see its dependents and dependencies.
        - Documentation is updated.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds? If so, please describe them.
      placeholder: e.g., "Manually documenting dependencies in the README."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, diagrams, or screenshots that might help us understand your request.
      placeholder: e.g., "See attached mockup for a proposed UI."
    validations:
      required: false
