name: Build and Publish Avalonia App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Ensure LFS files are present
        run: git lfs pull

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Show .NET SDK info
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish self-contained app (Windows x64)
        run: dotnet publish PlugHub.Desktop/PlugHub.Desktop.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishTrimmed=false --no-restore -o ./publish/win-x64
      - name: List published files for debugging
        run: Get-ChildItem -Recurse ./publish/win-x64/

      - name: Upload published app (all files)
        uses: actions/upload-artifact@v4
        with:
          name: PlugHub-Desktop-win-x64
          path: ./publish/win-x64/
