name: Mirror to GitLab

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          lfs: true
      - run: git lfs fetch --all
      - run: git remote add gitlab https://github:${{ secrets.GITLAB_PASSWORD }}@${{ vars.GITLAB_HOST }}${{ vars.GITLAB_PATH }}
      - run: git push --all gitlab
      - run: git push --tags gitlab
