name: Mirror to GitLab

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://git.enterlucent.com:1337/enterlucent/enterlucent-applications/plughub"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "git.enterlucent.com:1337"
          GITLAB_USERNAME: "project_45_bot"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} 
          GITLAB_PROJECT_ID: "45"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
