name: Mirror to GitLab

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mirror
        uses: xometry/gitlab-mirror-action@v1
        env:
          GITLAB_REPOSITORY: "https://git.enterlucent.com:1337/enterlucent/enterlucent-applications/plughub.git"
          GITLAB_USERNAME: "bot"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
 
