name: Mirror to GitLab

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
    contents: read    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror
      uses: xometry/gitlab-mirror-action@master
      env:
        GITLAB_REPOSITORY: "https://git.enterlucent.com:1337/enterlucent/enterlucent-applications/plughub.git"
        GITLAB_USERNAME: "your-username"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}