name: Rebuild Pages

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer ${{ secrets.USER_TOKEN }}"
