name: C# Test Matrix Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, macos-latest,
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Ensure LFS files are present
        run: git lfs pull          

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore -r win-x64

      - name: Build Solution
        run: dotnet build --configuration Release -r win-x64 -maxcpucount:1

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --verbosity normal