name: Build, Publish, and Create Release for Avalonia App

on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'  # Only run on tags matching e.g. v1.2.3

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Ensure LFS files are present
        run: git lfs pull

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Show .NET SDK info
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish self-contained app (Windows x64)
        run: dotnet publish PlugHub.Desktop/PlugHub.Desktop.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishTrimmed=false --no-restore -o ./publish/win-x64

      - name: List published files for debugging
        run: Get-ChildItem -Recurse ./publish/win-x64/

      - name: Compress published files
        run: Compress-Archive -Path ./publish/win-x64/* -DestinationPath ./publish/PlugHub-Desktop-win-x64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ./publish/PlugHub-Desktop-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
